name: Cron Reminders (external scheduler)

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes
  workflow_dispatch: {}

jobs:
  call-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke reminders endpoint
        run: |
          if [ -z "$APP_URL" ] || [ -z "$CRON_SECRET" ]; then echo "Missing secrets APP_URL or CRON_SECRET"; exit 1; fi
          curl -s -o /dev/null -w "%{http_code}" -X POST "$APP_URL/api/cron-reminders" -H "Authorization: Bearer $CRON_SECRET"
        env:
          APP_URL: ${{ secrets.APP_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
